### ISSUE TITLE
Issue with brainwallet

### ISSUE THREAD

**Issue by perone** [perone/protocoin#10]
```
import hashlib

import sys
sys.path.append('../protocoin')
from protocoin import keys

def brainwallet(num_bytes):
    hashobj = hashlib.sha256("my super secret password seed")
    return hashobj.digest()

priv_key = keys.BitcoinPrivateKey(entropy=brainwallet)
pub_key = priv_key.generate_public_key()                    #This line gives an AssertionError

....

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\Extensio
ns\Microsoft\Python Tools for Visual Studio\2.0\visualstudio_py_util.py", line 7
6, in exec_file
    exec(code_obj, global_variables)
  File "C:\git\myBlockChain\brainWalletTest\brainWalletTest.py", line 12, in <mo
dule>
    pub_key = priv_key.generate_public_key()
  File "../protocoin\protocoin\keys.py", line 180, in generate_public_key
    return BitcoinPublicKey.from_private_key(self.private_key)
  File "../protocoin\protocoin\keys.py", line 32, in from_private_key
    return klass(hexkey)
  File "../protocoin\protocoin\keys.py", line 20, in __init__
    curve=ecdsa.SECP256k1)
  File "C:\Anaconda\lib\site-packages\ecdsa\keys.py", line 36, in from_string
    (len(string), curve.verifying_key_length)
AssertionError: (63, 64)
Press any key to continue . . .
```

**Comment by perone** [comment]
Fixed on v0.2.
